import { Duck, DuckReward } from "@/types/duck";

export const mockDuck: Duck = {
  id: "duck-junkrat",
  name: "Pato Junkrat",
  slug: "pato-junkrat",
  theme: "Junkrat",
  rarity: "epic",
  level: 4,
  xp: 430,
  nextLevelXp: 500,
  maxLevel: 10,
  imageUrl: "/ducks/pato-junkrat.png",
};

export const junkratRewards: DuckReward[] = [
  {
    id: "reward-junkrat-1",
    duckId: "duck-junkrat",
    level: 1,
    name: "Pato Junkrat",
    type: "duck",
    description: "Desbloqueia o Pato Junkrat na sua coleção.",
  },
  {
    id: "reward-junkrat-2",
    duckId: "duck-junkrat",
    level: 2,
    name: "Borda temática Junkrat",
    type: "border",
    description: "Uma borda temática para destacar seu perfil.",
  },
  {
    id: "reward-junkrat-3",
    duckId: "duck-junkrat",
    level: 3,
    name: "Pin Junkrat",
    type: "pin",
    description: "Um pin colecionável do Pato Junkrat.",
  },
  {
    id: "reward-junkrat-4",
    duckId: "duck-junkrat",
    level: 4,
    name: "Acessório Junkrat na ilha",
    type: "island_accessory",
    description: "Um acessório temático para decorar sua ilha.",
  },
  {
    id: "reward-junkrat-5",
    duckId: "duck-junkrat",
    level: 5,
    name: "Arte digital HD",
    type: "digital_art",
    description: "Arte digital em alta definição do Pato Junkrat.",
  },
  {
    id: "reward-junkrat-6",
    duckId: "duck-junkrat",
    level: 6,
    name: "Ravelbox",
    type: "ravelbox",
    description: "Uma Ravelbox como recompensa especial.",
  },
  {
    id: "reward-junkrat-7",
    duckId: "duck-junkrat",
    level: 7,
    name: "Acessório lendário de ilha",
    type: "island_accessory",
    description: "Um item visual mais raro para a ilha.",
  },
  {
    id: "reward-junkrat-8",
    duckId: "duck-junkrat",
    level: 8,
    name: "Junkrat Rei",
    type: "skin",
    description: "Visual evoluído do Pato Junkrat.",
  },
  {
    id: "reward-junkrat-9",
    duckId: "duck-junkrat",
    level: 9,
    name: "Borda lendária",
    type: "border",
    description: "Uma borda lendária para o perfil.",
  },
  {
    id: "reward-junkrat-10",
    duckId: "duck-junkrat",
    level: 10,
    name: "Ravelbox",
    type: "ravelbox",
    description: "Recompensa final da trilha do Pato Junkrat.",
  },
];
